version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "next"
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "next-auth"
      - dependency-name: "@prisma/client"
      - dependency-name: "prisma"
      - dependency-name: "bcrypt"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Paris"
