template: |
  ## Deployment Status

  | Environment | Status | Deployment Date | URL |
  |------------:|:------:|:---------------:|:----|
  | Development |        |                 |     |
  |     Staging |        |                 |     |
  |  Production |        |                 |     |

  ### Test Status

  | Test Type         | Status | Coverage |
  |-------------------|:------:|:--------:|
  | Unit tests (Jest) |        |          |
  | Linter (ESLint)   |        |          |
  | Build             |        |          |

  ## What's Changed

  ### Added
  {{#changes added}}
  * {{ this.title }} ({{ this.pullRequest.html_url }})
  {{/changes}}

  ### Changed
  {{#changes changed}}
  * {{ this.title }} ({{ this.pullRequest.html_url }})
  {{/changes}}

  ### Fixed
  {{#changes fixed}}
  * {{ this.title }} ({{ this.pullRequest.html_url }})
  {{/changes}}

  ### Security
  {{#changes security}}
  * {{ this.title }} ({{ this.pullRequest.html_url }})
  {{/changes}}

categories:
  - title: "Added"
    label: "release:add"
    description: "New features"
  - title: "Changed"
    label: "release:change"
    description: "Code refactoring"
  - title: "Fixed"
    label: "release:fix"
    description: "Bug fixes"
  - title: "Security"
    label: "release:security"
    description: "Security improvements"
