services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: locklite
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: locklite_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
