services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - psql_data:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:5432"

volumes:
  psql_data:
